### ISSUE TITLE
MariaDB (mysql fork) support

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#100]
There is no super-major changes in it, so i suggest to support it in TS-N. Or atleast notice user about mariadb in ranksystem installer.

**Comment by Newcomer1989** [comment]
For the Ranksystem there is no difference between MariaDB and MySQL. All functions the Ranksystem uses will work also with MariaDB.
For your information I am also using a MariaDB since years. So the Ranksystem is developed on a MariaDB ;-)

I change the text inside the dropdown on installation. But most sysadmins should know that already, if they have a MariaDB :-)
