### ISSUE TITLE
Statistics page - client version donut has wrong sum of 'others'

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#102]
May i ask, does TSNRanksystem recognize serverquery version of clients?
I have versions graphic on my system
3.0.19.4 [Build: 1468491418] - 394 users
3.1 [Build: 1472203002] - 3 users (beta client)
3.0.23 [Build: 1463662487] - 1 user (android)
2 parts of 0
and 8 users recognized as 'Other versions'.
But what are 'other versions'?
I mean, if that's serverquery clients - can you make them recognizable too?

Same question about Countries - 2 of the list recognized as 'Other countries'. Maybe it is 127.0.0.1 and it is should not be counted in ranksystem or counted as 'local machine'?

**Comment by Newcomer1989** [comment]
> May i ask, does TSNRanksystem recognize serverquery version of clients?
The Ranksystem doesn't count serverquery clients on the donut charts. The serverquery clients will be ignored completly for the serverstats. So the total clients number and the recorded online time are without serverqueries.

> But what are 'other versions'?
That should be other client versions. Perhaps older version, which are not more using by much clients. Or special builds of a client version (pre-build..).
To get a list of this versions you can run the following sql command on your Ranksystem database.
`SELECT version, count(version) as count FROM user GROUP BY version ORDER BY count DESC;`

**Comment by bykidi** [comment]
Got it. Thanks

**Comment by Newcomer1989** [comment]
I checked the summary of the other versions and found there a mistake inside the calculate operation (shame on me).
This will be fixed with release 1.1.2

The nations donut (countries) should be correct. This can differ to the number of "Total users" due there are not for all ip addresses countries resolvable (dependent on the server version and their country database http://forum.teamspeak.com/threads/68544-Wrong-or-no-country-city-or-Flag-shown-in-weblist-and-client)

**Comment by Newcomer1989** [comment]
release 1.1.2 is out
