### ISSUE TITLE
Branches and description

### ISSUE THREAD

**Issue by Pe46dro** [Newcomer1989/TSN-Ranksystem#103]
I suggest you to use branches to separate `Beta` or `Dev` and `Master`, that allows user to test new function but they will know that it can have bugs and users that use it all days will not suffer consequences of bugs or absence of functions like the possibility to edit user stats.
Furthermore the commits it's better if they contain a description not only `release 1.x.x` or `made changes` that results vague.

**Comment by Shad86** [comment]
So your main suggestion is to have an extra Beta or/and Dev branches.

Because at the moment there is no current beta or dev branch available, it only exists the "stable / Master" branch

**Comment by Newcomer1989** [comment]
For a list, what was changed inside a release -> see the changelog here: http://ts-n.net/ranksystem.php

Like Shad86 already described, there is no beta or dev, what is shared with GitHub at the moment. And I do not think I will ever made a dev or beta public. It will stay for only a few count of persons.

I would not be able to handle the issue reports. There would comes error reportings, which are already fixed in newer version(s) and so on...
That would be to much. This project is a hobby and no commercial project, where several people are working 9 to 5 on it ;-)
