### ISSUE TITLE
Your PHP version (5.4.16) is below 5.5.0. Update of PHP needed! Shuttin down!

### ISSUE THREAD

**Issue by Sqveeze** [Newcomer1989/TSN-Ranksystem#106]
I get this message when i try to manually start the ranksystem but the ranksystem also logs this on the cron run.

CRITICAL  Your PHP version (5.4.16) is below 5.5.0. Update of PHP needed! Shuttin down!

The problem is, while i have 3 PHP version on my system (Because Plesk menages them separately) i run the cron with php 5.6 but the error still comes. Why? Only the main control panel (Plesk) uses the 5.4 everything else, crons, websites, etc runs on 5.6 or 7

crontab -u ranksystem -l

30      *       *       *       *       /opt/plesk/php/5.6/bin/php -f 'path/to/ranksystem' -- 'check' '>/dev/null' '2>&1'

**Comment by Shad86** [comment]
i think you have cli installed? -> php -v - i think php5.5 must be loaded.

The other case is, you should definitely decide which php you want to use and then use it on all.

5.4 is also very outdated so that it would be good to eliminate it so that you only have php 5.6 + php 7

regards

Shad86

**Comment by Sqveeze** [comment]
php -v - i says 5.4.16 is loaded, however that's because i ran the command
on the root user via ssh. The cronjob itself is running from the plesk
admin panel via the user of the web services. And the PHP version was set
to 5.6 for cronjobs. The problem is when i run the command manually via 5.6
php. Ranksystem still says i ran it from 5.4 i guess this a bug that
ranksystem has. I guess ranksystem + plesk cant work with each other

2016. szept. 16. 11:04 ezt írta ("Shad86" <notifications@github.com>):

**Comment by Shad86** [comment]
And as i said 5.5+ must be loaded.

As on the TsN-Site stands:

**So as the requierments on the tsn site says:**

> PHP 5.5.0 or higher with PDO support; PHP 7 is supported!`

**The next things is:**

The main reason why it will not work over short or long (or you will run into troubles).

If you stop or start the ranksystem over the Webinterface it will take the main loaded php version, what in your case is 5.4.

don't use software on your system whats outdated since over an year - that's a big security risk in my eyes.

and im not joking php 5.4 support ended on "3. Sep 2015"

here is some guides or/and information (as i can see it isn't a big deal to rise 5.4 to 5.6):

http://php.net/eol.php

As i also was able to see since Plesk 11.5 it shouldnt be a problem to use php 5.6 as main loaded php version.

regards

Shad86

**Comment by Newcomer1989** [comment]
> Ranksystem still says i ran it from 5.4 i guess this a bug that ranksystem has. I guess ranksystem + plesk cant work with each other

This is not a bug of the Ranksystem or any problems, what the Ranksystem has with Plesk. It might be, that your plesk are using 5.6, but the Ranksystem get startet with exec command, so it uses the PHP, which are default on your system (in your case PHP 5.4.16).

Be sure your system will use PHP 5.5.0 or higher, when you run the PHP command on your shell!

Like Shad86 described you could remove the PHP 5.4.16 on your system to solve your problem. I can't believe that Plesk will only runs with an outdated PHP version. Perhaps you should also check there are updates available for Plesk.

I will close this thread. It is only a problem of system administration.
