### ISSUE TITLE
ERROR Fehler 1024: invalid serverID

### ISSUE THREAD

**Issue by koenigheine** [Newcomer1989/TSN-Ranksystem#107]
I can't start the Rankbot because of this Error:

ERROR     Fehler 1024: invalid serverID

My problem is that there is no option to fill in the ServerID.

**Comment by Newcomer1989** [comment]
A little bit more informations would be nice. Otherwise it is not possible to help you. What you have exactly done? Please describe your steps, that we can follow you..

It is true, there is no server ID, which will be used for the connection. The connection to the TeamSpeak server will be established with the Voice Port.

Please post here the first 15-20 lines of your ranksystem.log after restarting the Ranksystem Bot.

Also it would be nice to know... Run the Ranksystem on the same machine the TeamSpeak server runs? How much server are running on this TeamSpeak instance? Which server ID has your server?

**Comment by Newcomer1989** [comment]
Closed due no response
