### ISSUE TITLE
mysql optimisation

### ISSUE THREAD

**Issue by ryanmemer** [Newcomer1989/TSN-Ranksystem#113]
Since the update I've been experiencing extraordinary cpu usage from the rank system. 

I don't suppose by the next update you could optimise the mysql usage throughout the system? The old version was perfectly fine for my hardware specification, now it's looking like I have to upgrade :P

**Comment by Newcomer1989** [comment]
Which old version are you meaning? 0.13-beta?

Since 1.00 the Ranksystem scans continuously (each second) for new user and calculate minor things for the stats page. Before this it scans once time a minute. Sure it need ~60x more resources.

To save ressources you can activate the "slowmode" about the webinterface. A restart of the bot is required. Try the "high delay", this should save your cpu.

But sure, I am looking everytime for optimizations and implement this. Also the code is open source. So feel free to look yourself for better ways or disable the part of code you do not need.
