### ISSUE TITLE
Reset password for the Webinterface - and other questions

### ISSUE THREAD

**Issue by ngx3** [Newcomer1989/TSN-Ranksystem#116]
1. I'm not sure this is default, but the bot is giving server groups but not removing the guest rank?

2. When logging into webinterface it always doesnt allow me to login sometimes even though the user and password is right. I know that it has anti flooding for logging in once password is wrong, but this isn't the case. Could be a bug.

3.  Is the bot suppose to join the channel? No way to tell if everythings working, besides the log file.

**Comment by Shad86** [comment]
Well the query should connect to the ts3-Server - also would it be helpfull if you provide the log (remove sensitiv data if there are some in)

**Comment by ngx3** [comment]
So I login for the first time and it doesn't allow me in then I see this error, but only when I connect multiple times. But when the 300 seconds are finished I can login fine. Seems like a bug.

`2016-10-01 16:31:17.005425   WARNING   Much incorrect logins detected on the webinterface. Blocked login for 300 seconds! Last access from IP --------.`

My log file.
```
2016-10-01 20:42:28.711898   INFO      Initialize Bot...
2016-10-01 20:42:28.721531   INFO      Check Ranksystem database for updates.
2016-10-01 20:42:28.721647   INFO        No newer version detected; Database check finished.
2016-10-01 20:42:28.721935   INFO        Ranksystem Version: 1.1.0
2016-10-01 20:42:28.721990   INFO      Connect to TS3 Server (Address: "teamspeak ip" Voice-Port: "9987" Query-Port: "10011").
2016-10-01 20:42:29.151973   INFO        Conenction to TS3 Server established.
2016-10-01 20:42:29.241720   INFO        Joined to specified Channel.
2016-10-01 20:42:29.241848   INFO      Bot starts now his work!
```

**Comment by Newcomer1989** [comment]
Point 1:
All said by Shad86. Only one thing more. The guest group is by default temporary (ts3 perm: b_group_is_permanent), so it get automatically removed by your ts3server, if you set one permanent group.

Point 2:
You changed the host of the Ranksystem?
There is actual no way to change the password directly via the Ranksystem. Only way actual is to do this manual.
You can install a second instance of the Ranksystem. After installation copy the password out of the database of the second instance
`select webpass from _ranksystem1_.config;`
and put this inside your actual running (first) instance.
`update _ranksystem2_.config set webpass='_output of the select above here_';`
Replace ranksystem1/2 with your database names.

Point 3:
This looks good. I do not understand where your problem is..

**Comment by Newcomer1989** [comment]
release 1.1.2 is out; a function to reset the passwort is part of them
