### ISSUE TITLE
never disconnecting

### ISSUE THREAD

**Issue by abstractedits** [Newcomer1989/TSN-Ranksystem#129]
Hey guys,
for some reason the bot connects and seems to work fine, but it never disconnects from the server and the log also seems to be messed up. The cronjob should be set up fine every 10 min on my linux debian VPS: */10 * * * * php /var/www/html/ranksystem/worker.php check >/dev/null 2>&1
Please help me,
thanks for any answers

**Comment by Newcomer1989** [comment]
The Ranksystem is designed as Bot and if all works it should never disconnect. So that is no bug, it's a feature. ;-)

If you wish to stop the Ranksystem Bot, you should disable your cronjob (the cron has the job to restart the Ranksystem Bot, if its crashed) and stop it after about the webinterface.

**Comment by abstractedits** [comment]
ohh ok i see, thanks for the quick reply.
But why is the log not working properly then ?
A user was added to the ranksystem and also gained a servergroup from it, but its not in the log...

**Comment by Newcomer1989** [comment]
Please check where you configurated the log (logpath) inside the webinterface.

Also be sure, the logpath (the whole folder) is writeable by the user with this the Ranksystem runs.
