### ISSUE TITLE
1.1.2 issues

### ISSUE THREAD

**Issue by SuperArmySoldiers** [Newcomer1989/TSN-Ranksystem#152]
@Newcomer1989 ... I have posted the issues. Closing and locking threads because im pointing out issues is not cool. Enjoy the power trip.

I posted 2 screen shots of the errors in 1.1.2.
http://puu.sh/s1DsD/9de44fd14b.png
http://puu.sh/s1Dvg/8bbc4189ba.png

I am not a developer. I do not know what the issue is. Hence I am posting here.

I personally did not update the program. Someone else did. He followed step by step the instructions on your website.

> How to UPDATE:

This HowTo is to update from 1.00, 1.0.1, 1.0.2, 1.1.0 or 1.1.1 to version 1.1.2. If you still using 0.13-beta, you should first update to 1.00 and then update to the latest release.

1. Download and unzip "ranksystem x.x.x.zip".

2. Backup the "other/dbconfig.php" on your websever. We recommend to backup the whole webspace, the TeamSpeak server and also the database!

3. Stop the sheduler (cron/task) for the worker.php and also stop the Bot (php worker.php stop). Be sure, there is no TSN Ranksystem connected to your TeamSpeak!

4. Upload the whole unzipped folder to the your webspace and grant permissions to the webuser (i.E. chown -R www-data /var/www/Ranksystem).

5. Restore the saved "other/dbconfig.php".

6. Check php-curl is installed on your webserver (linux: apt-get install php-curl)!

7. Reactivate the sheduler (cron/task) for the worker.php (see installation point 4).

It deleted our database which is annoying and unfortunately the last database we had was 11 days old. 
There is no mention of needing to back up the database in your instructions. 

Due to these issues we have gone back to the alpha you sent me.
Remember... I offered to help test this. Giving my free time. The least you can do is not lock threads and ignore errors in your code. I clearly gave you screen shots of the issues.

**Comment by Shad86** [comment]
> There is no mention of needing to back up the database in your instructions.

thats funny because you posted by yourself point 2 where newcomer mentioned it ;)

> 2. Backup the "other/dbconfig.php" on your websever. We recommend to backup the whole webspace, the TeamSpeak server and also the database!

> It deleted our database which is annoying and unfortunately the last database we had was 11 days old.
There is no mention of needing to back up the database in your instructions.

well, thats why it is recommend to do at least a backup before you update ;) (and i think everyone would say the same - so in that case also if it sounds hard/harsh -> your fault)

second point is a database shouldn't be deleted if you are only update (there is no reason and also no option like that in it in the update procedure) - i think your guy who did the update did a fresh installation, because only then the database would be deleted.

**Comment by SuperArmySoldiers** [comment]
@Shad86 ha your right it is there. I shall point that out to the guy who did the update!
The database issue cant be fixed. We have moved on and started again. Its a mistake that we did not back it up again. But something happened when the program was updated. 

But the other issues still stands.

**Comment by Shad86** [comment]
@Newcomer1989 also mentioned and i also think that this issue comes from that, that your guy didn't do an update and did instead a fresh install and thats why you lost your database.

I think that because of you prior post from issue #149 

> Error
SQL query:

CREATE TABLE config (
webuser text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
webpass text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
tshost text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
tsquery int(5) NOT NULL DEFAULT '0',
tsvoice int(5) NOT NULL DEFAULT '0',
tsuser text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
tspass text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
language text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
queryname text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
queryname2 text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
grouptime text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
resetbydbchange int(1) NOT NULL DEFAULT '0',
msgtouser int(1) NOT NULL DEFAULT '0',
upcheck int(1) NOT NULL DEFAULT '0',
uniqueid text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
updateinfotime int(8) NOT NULL DEFAULT '0',
currvers text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
substridle int(1) NOT NULL DEFA[...]
MySQL said: Documentation

#1046 - No database selected

because this only can come up if you do a fresh installation

regards

Shadow86

**Comment by Newcomer1989** [comment]
>  I shall point that out to the guy who did the update!

Then please ask these guy, what exactly he has done! He did not the normal update procedure..

Perhaps try to install the Ranksystem it complete fresh on your system. And have a look the posted errors (your two screenshots) comes again on the fresh installation,

**Comment by SuperArmySoldiers** [comment]
> Perhaps try to install the Ranksystem it complete fresh on your system. And have a look the posted errors (your two screenshots) comes again on the fresh installation,


We did in the end. Those errors in my screen shots come up.

**Comment by Newcomer1989** [comment]
You installed this in an empty folder or you were using the old folder?

**Comment by Newcomer1989** [comment]
Closed due no response.
