### ISSUE TITLE
The Bot is loosing the connection and didn't reconnect

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Newcomer1989/TSN-Ranksystem#175]
I have to restart the Bot one or two times the day.

I can't see anything in the Ranksystem log.

Greetz Bl4CkGuuN

**Comment by Shad86** [comment]
Well usually there should be something in the logfile (dont forget to check also the "ranksystem.log.old" file), 

but well thats why you usually should setup a cronjob, just because of that if for any reason the bot loses connection or may is crashing.

In my case i have to say it never lost connection or crashed on my server and i used the 1.1.3 for a whole week, without any issues.

**Comment by Bl4CkGuuN** [comment]
Ok, maybe I should update :D

**Comment by Newcomer1989** [comment]
closed due no response
