### ISSUE TITLE
[BUG] Bot doesn't start, no logs where written

### ISSUE THREAD

**Issue by hikomedia** [Newcomer1989/TSN-Ranksystem#187]
I have tried to fix the bot multiple times but it just doesn't work, check the requirements enabled the extensions.
Bot doesn't connect to server, server query is correct too
Xammp 3.2.2
Windows 7

**Comment by Newcomer1989** [comment]
How did you start the Ranksystem?

What you get, if you run the worker.php via command line?
`php worker.php start`

**Comment by RickardPettersson** [comment]
I have the same problem but on windows server 2012 r2 and php 7.X

When i running jobs\bot.php then log file says 

2016-12-02 20:44:15.136077   INFO        Connection to TS3 Server established.
2016-12-02 20:44:15.880712   NOTICE      No channel defined where the Ranksystem Bot should be entered.
2016-12-02 20:44:15.881575   INFO      Bot starts now his work!
2016-12-02 20:44:20.896431   INFO      Received signal to stop. Shutting down!

but when i running "php worker.php check" and the command line says "Starting the Ranksystem Bot." and then running worker.php status its says "Starting the Ranksystem Bot.".

But no logs when running worker.php.

Please help

**Comment by Newcomer1989** [comment]
I think it could be the missed COM extension. Please make sure you have only one PHP installed and/or the `php` command shows to the configured PHP version.

On windows the Ranksystem try to get the process ID (with that the Ranksystem will run) about the COM module.

Please also use the correct user (-> web user) to start the Ranksystem, also for the `worker.php`! Do not use an administrator account for that!
The user you are using, needs the permissions to exec(ute) commands via PHP and needs to see his own process via `wmic` command. Sure also the write permissions for the logs folder are important. The user needs the permissions to create the "pid" file inside the "logs" folder.

Try one more thing:
1. Create a file with the name "pid" inside the "logs" folder
2. Start the Ranksystem via `php jobs/bot.php`

If it runs with this steps, you do not fullfill the requirements. In that case check the described things above, because one of this must be it!

**Comment by Newcomer1989** [comment]
closed due no response on our post
