### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#215]
Upgraded my PHP from 7.0 to 7.1 today.
No errors in the log file. Ranksystem just connects and instantly disconnects.

2017-01-06 19:30:37.585227   INFO      Connect to TS3 Server (Address: "127.0.0.1" Voice-Port: "9987" Query-Port: "10011").
2017-01-06 19:30:37.585165   INFO        Ranksystem Version: 1.2.1
2017-01-06 19:30:37.585003   INFO        Check files permissions [done]
2017-01-06 19:30:37.568101   INFO        Check files permissions...
2017-01-06 19:30:37.567406   INFO        No newer version detected; Database check finished.
2017-01-06 19:30:37.567276   INFO      Check Ranksystem database for updates.
2017-01-06 19:30:37.555913   INFO      Initialize Bot...

<19:37:04> "RankSystem from 127.0.0.1:34732" connected to channel "Welcome!"
<19:37:04> "RankSystem from 127.0.0.1:34732" dropped (connection lost)

PHP 7.1.0-5+deb.sury.org xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0-5+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies

**Comment by Shad86** [comment]
Hello,

you still sure all your other settings correct?

and you tried it again, to be sure it isn't an network issue.

regards

shad86

**Comment by bykidi** [comment]
this just can't be network error because on 7.0 everything worked fine

**Comment by Shad86** [comment]
Be sure that all our needed extensions also got an update.

We have an eye on it, as soon as there is enough time for it Newcomer will take a look on it.

**Comment by Newcomer1989** [comment]
You can also try to debug the Ranksystem to get the error.
1) Go to file jobs\bot.php and comment the line `error_reporting(0);` out (change to `//error_reporting(0);`)
2) Open a command line and run the jobs\bot.php manual
`sudo -u www-data php jobs\bot.php`
replace www-data with your correct webuser
3) Post the output here...

**Comment by bykidi** [comment]
Insta-disconnect error can be fixed by merging this PR
https://github.com/planetteamspeak/ts3phpframework/pull/21

Commented out error reporting but log file is still empty.
Now ranksystem disconnects a bit later with this PR
<13:31:57> "RankSystem from 127.0.0.1:48954" connected to channel "Welcome!"
<13:31:57> "RankSystem from 127.0.0.1:48954" is now known as "RankSystem"
<13:31:57> "RankSystem" switched from channel "Welcome!" to "╔ Admins"
<13:32:02> "RankSystem" dropped (connection lost)

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/21742334/7d3e3572-d4fd-11e6-84dd-c1b514ff3540.png)

**Comment by Newcomer1989** [comment]
With the next release, we will implement the support for PHP 7.1.

At the moment I would recommend to use PHP 7.0 instead.

**Comment by bykidi** [comment]
Can we get a hotfix for php 7.1 support? Its been 10 days since my ranksystem is not working

**Comment by Shad86** [comment]
Thats the "bad" side on it, for wanting always the newest from the newest.

You just have to wait for it until its done.

Newcomer have to work and to study. So he tries to bring it out as fast as he can.

**Comment by bykidi** [comment]
@Shad86 I know. I work too. 8 hours per day.
But based on official changelog - newest ranksystem is ready for php 7.1 (https://ts-n.net/ranksystem.php)

**Comment by Shad86** [comment]
Thats just not right.

Based on the Changelog there is only php 7.0 support atm

1.2.2 (2017-XX-XX) isnt rolled out ;)

https://ts-n.net/ranksystem.php#changelog

And the current requirements also says:

> PHP 5.5.0 or higher with PDO support; PHP 7 is supported!

So you have to wait until its done its not only our fault if your not fulfill the requirements they are clearly written on the site.

And as i said he not only has to work he also has to study so after 8 hours of work his day isn't over ;) - 

But he will roll out the new version as soon as it stable, because it doesn't make sense to roll out an update what crashes your bot ;)

**Comment by Newcomer1989** [comment]
To bring a new support (PHP 7.1) would not be a hotfix, because it is no fix. It is rather a feature.

And I will not implement features hot. That has to be tested as well. And this needs time. As Shad86 already describes I study alongside a full-time job. My job needs actually more than 8 hours a day. Also I have to prepare for clauses. So my time is at the moment near zero.

Sorry, but this project is and will ever be a hobby project. For that what you promote, you normally have to pay a lot of money and the faster you want it the more expensive it would be.

**Comment by Newcomer1989** [comment]
release 1.2.2 is out now

**Comment by bykidi** [comment]
yey
