### ISSUE TITLE
Top Users

### ISSUE THREAD

**Issue by beals1pt0** [Newcomer1989/TSN-Ranksystem#229]
The top user section seems bugged after latest patch i click it and it never opens anything

**Comment by Shad86** [comment]
please provide us more informations pls

**Comment by Shad86** [comment]
you mean:
![topuser](https://cloud.githubusercontent.com/assets/18570683/22218418/e98bfe5c-e1a6-11e6-9ce0-eac6208d3506.png)

if so for me all of them are loading

**Comment by bykidi** [comment]
@beals1pt0 add your site to whitelist of your adblocker

**Comment by Newcomer1989** [comment]
I could not imagine, what it should have to do with the update of the Ranksystem, that you have to whitelist it inside the adblocker. There are no special images/banner or new javascripts, which should get blocked.

On the update the JS-Code where moved. Perhaps you have a problem with your browser cache. Try to force the reload of the cached things in your browser (STRG + F5).
Otherwise be sure, the update was successfully and the new files could create on your webserver (check the ranksystem.log for this).

**Comment by beals1pt0** [comment]
it was my ad blocker that was blocking it thank you

**Comment by bykidi** [comment]
@beals1pt0 rename the issue users could find this easier

@Newcomer1989 Try uBlock Origin with following lists:
![default](https://cloud.githubusercontent.com/assets/1337953/22236852/540dac7c-e219-11e6-9310-06b37cfb976b.png)
![2](https://cloud.githubusercontent.com/assets/1337953/22236877/74e42958-e219-11e6-81a0-898803b4b903.PNG)
![3](https://cloud.githubusercontent.com/assets/1337953/22236883/7c5864c4-e219-11e6-92ca-646633d9a9ea.PNG)



(p.s.: translating back from russian so might be wrong)
