### ISSUE TITLE
Ability to start ranksystem using custom user account on linux

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#239]
Reason for this? Every time i restart my apache - ranksystem goes down because of the user used to start ranksystem is www-data. If i use custom created user - ranksystem works fine without dropping connection.

**Comment by mightyBroccoli** [comment]
I am also hosting my ranksystem with an apache also controlled by the user www-data. That is completely normal. Maybe your www-data user is not allowed to use all php functions and crashes because of that?

**Comment by bykidi** [comment]
@mightyBroccoli no idea, but i think that www-data is not the user that should run the ranksystem.

**Comment by Shad86** [comment]
Well if apache gets restartet - it can be that services that are belonging to it they are getting restartet too (depends on how it is set up) so mostly php gets also restarted, when the apache is restarted.

and if php gets restarted its logical that the ranksystem went down because the php service gets terminated and then started again

So in that case all are correct.

If you start it on a other user its just the thing that apache or php doesnt have the right to terminate it ;) - and if thats a good idea, i can say no it isn't.

Next thing is - thats why we say in the installation guide that you have to add a cronjob

So the maximum "lose of time" would be 10 min and that isn't that much in my opinion.

**Comment by Newcomer1989** [comment]
Have you had a look to the ranksystem.log? There stands anything why it stops?

**Comment by bykidi** [comment]
@Newcomer1989 seems like you just deleted your post...

No, there is no error logs. We just should use something different, not www-data. Fixed :)

**Comment by Newcomer1989** [comment]
I deleted, cause my answer was to fast after flying over the posts.. I read again the thread and thought Shad86 has described all needed. So please forgot my post for the log entry.

The problem in your case is/was that the Ranksystem gets started as child of your main process of your webserver (apache2). For sure the Ranksystem get started as child of the webserver, if you using the start/stop/restart function about the webinterface.
If you start the Ranksystem over the command line `sudo -u www-data php worker.php start`, it is a separated process. On restarting the webserver in this case, the Ranksystem will not be dropped (cause it is now no child of your webserver).

**Comment by bykidi** [comment]
@Newcomer1989 So basicly the solution is not to restart ranksystem using the webpanel...
I'm fine with that 👍
