### ISSUE TITLE
Server group not changed

### ISSUE THREAD

**Issue by manercraft** [Newcomer1989/TSN-Ranksystem#246]
Hello, I have install your TSRankSystem, configure etc
And I have test with a friend, when he needs to switch groups, He does not change group. While on the users stats page, its next group is update

**Comment by Shad86** [comment]
What database your using? mysql or mariadb (version -> mysql -v)

You sure you set the permissions right? Because form me it works as intend

regards

Shad86

**Comment by manercraft** [comment]
![leagueclientux_2017-02-07_21-32-34](https://cloud.githubusercontent.com/assets/1338257/22710270/fb340848-ed7c-11e6-9341-e45062f0e860.jpg)

I used the serveradmin query, it has all permissions no ?

**Comment by Shad86** [comment]
maybe damaged or broken, i didn't had any problems with any Version, if it comes to Server group assign and server group revoke

**Comment by Shad86** [comment]
I have also a next question you mean the normal rank up?

And can you send us a log, if its still not working.

**Comment by manercraft** [comment]
https://hastebin.com/egemiqajiz.scala

![chrome_2017-02-07_22-26-06](https://cloud.githubusercontent.com/assets/1338257/22712253/75bb3404-ed84-11e6-8985-b9c9917691ec.jpg)
/!\ I have disabled the rank putting 9999999 /!\
But before, I have set 60=>5,600=>6 etc

**Comment by Shad86** [comment]
The only thing i can say is, if you change the rankup  while its running you can run into troubles and the ranksystem may mess around so, it is always recommend to stop the ranksystem and comment out the crontab while you setup the rankup definitions.

So i would suggest you try it again, and also make sure you use the latest ranksystem version (current 1.2.2).

You also can try a fresh install so that it is sure that the mysql tables are may not broken. (if its possible)

regards

Shad86
