### ISSUE TITLE
Help bot is not starting and no logs (Xampp)

### ISSUE THREAD

**Issue by CreeperHD** [Newcomer1989/TSN-Ranksystem#281]
Hey,
i have a problem i can't start the bot and it is not creating logs pls help me
i have a windows server with xampp

sry for my bad english

**Comment by Artapel** [comment]
Can you provide a screenshot?

Can you tail -f the logs file? from the command line?

You will need to provide much more information

**Comment by CreeperHD** [comment]
it is not creating a log file

**Comment by bit2gb** [comment]
... you dont help us with information so in this way we cant help

**Comment by Shad86** [comment]
for windows it was always hard for me to find a really good working solution... Most times newcomer found out where the problem was - but also he mostly needed 20-30min for it...

But if you want i can offer you to host it on my Server - i do hosting it already for 3 guys.

So as long as the tsn teamspeak is up just visit it and write to me "Shad86" if you need a hosted solution.

**Comment by CreeperHD** [comment]
Shad86 okay When are you on the Ts3

Sry for my bad English

**Comment by Shad86** [comment]
Ich hab in der Verwandtschaft derzeit einen Todesfall bitte schreib mir an
rank@hdf-multigaming.de sobald ich wieder Luft habe schreib ich dir dann
CreeperHD <notifications@github.com> schrieb am Do. 30. März 2017 um 20:00:

**Comment by NimaGame** [comment]
Hi , I have the same problem , but the bot works when I start it from jobs/bot.php.
Can you please help me?
