### ISSUE TITLE
Cronjob

### ISSUE THREAD

**Issue by KingRick2000** [Newcomer1989/TSN-Ranksystem#282]
Hello,

which cronjob do i have to add? Your website is down so i dont know :( my stats are always too late

**Comment by bykidi** [comment]
Managing cronjob's is so easy with Webmin. Install it.

**Comment by eNNercY1337** [comment]
Why install Webmin if you can simply use crontab –e and then edit it with nano?

 

Also here the cronjob you’ve asked for.

 

*/10 * * * * php /xxxx/xxxx/xxxx/xxxx/worker.php check >/dev/null 2>&1 

 

Perhaps depending on which user your webserver runs you’ll need to run the cronjob with a different user otherwise you run into perm. Issues with the PID not being able to be deleted once you try to manually start/stop/restart the bot.

 

Incase www-data -> */10 * * * * sudo –u www-data php /xxxx/xxxx/xxxx/xxxx/worker.php check >/dev/null 2>&1 

 

 

Von: bykidi [mailto:notifications@github.com] 
Gesendet: Sonntag, 19. März 2017 11:45
An: Newcomer1989/TSN-Ranksystem
Cc: Subscribed
Betreff: Re: [Newcomer1989/TSN-Ranksystem] Cronjob (#282)

 

Managing cronjob's is so easy with Webmin. Install it.

**Comment by KingRick2000** [comment]
Which option do i have to chose? 

http://prntscr.com/embz0n
http://prntscr.com/embzq0
Is this option right?

**Comment by bykidi** [comment]
You only have to execute 'php /path/to/worker.php check' command every 10min - 1hour. That's it.

**Comment by Shad86** [comment]
> Which option do i have to chose?
> 
> http://prntscr.com/embz0n
> http://prntscr.com/embzq0
> Is this option right?

It looks okay for me
