### ISSUE TITLE
Deleting a client

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#334]
When comes the function to delete a specific user out of the ranking system?

**Comment by bykidi** [comment]
Probably never because the project itself seems to be abandoned by Newcomer :(

**Comment by Shad86** [comment]
Well, a user is always in the ranksystem as long as he exists on the teamspeak database.

so if you want to remove him out of the ranksystem, you have to remove him from the teamspeak database.

If under core is activated this one:
![clean clients](https://user-images.githubusercontent.com/18570683/28501543-31c6a922-6fde-11e7-8551-48b9355f5503.png)

it also cleans up all 24 hours. Its not recommended to lower this check to a lower Value then i would say 6 hours. Because it interacts with the database of teamspeak an as more as it have to interact with it as more laggs it can cause on your teamspeak (for example, if you would do a check each 5 min.).

If you just want to reset a user, thats possible with that (under core in the webinterface):
![resett time](https://user-images.githubusercontent.com/18570683/28501527-b8466d80-6fdd-11e7-8baf-2edfeb0eb064.png)


Just saying because i think you guys didn't know about it, you can click on nearly every word in the Webinterface like "exception mode, clean clients, and so on..." and you will get an explanation what it is and waht it is doing.

regards

Shad86
