### ISSUE TITLE
Nextup

### ISSUE THREAD

**Issue by EGXZ** [Newcomer1989/TSN-Ranksystem#387]
Hey, all.

I wanted to ask why the command nextup doesn't work since the last update ?

Feelsbadman :(

**Comment by Shad86** [comment]
you sure, that you use "!nextup" and not "nextup"?

**Comment by EGXZ** [comment]
Holy fuck, right. 

Is that new ? the exclamation point ?

**Comment by Shad86** [comment]
in version 1.2.3 yes:

> + added new parameter to messages (rankup notification & command !nextup) with the name of the user (recipient)

https://ts-n.net/ranksystem.php#changelog

**Comment by Newcomer1989** [comment]
To complete the answer:
The command was ever !nextup, since version 1.1.2.

> 1.1.2 (2016-10-30)
> + added command "!nextup"; TeamSpeak user can write the command to the Ranksystem bot via private text message and will get their needed time for the next rank up

It was for a time possible to use it without the exclamation point. But we decided it is a better way to force all commands to use with the exclamation point, even you would shutdown it by writing any random message with i.e. the word "stop" in the channel-chat the bot is sitting in.
