### ISSUE TITLE
Boost function

### ISSUE THREAD

**Issue by Artapel** [Newcomer1989/TSN-Ranksystem#389]
Hi Guys. 
Quick Q. we experimented with the boost function and used one of the rank tags as the boost tag. now a few (50+) users lost their rank tag.

Is there anyway to have the rankbot reissue the tags for the level they are currently on?

**Comment by Newcomer1989** [comment]
This should be repaired automatically with the next rank up of that persons.

Otherwise you can also give that users any higher group, which is part of the rank up definition, directly on the TeamSpeak server. The Ranksystem should remove that group and give the person the correct one. Then also the stored information in the database should be correct.

**Comment by Newcomer1989** [comment]
You wrote "a few 50+".. I understand with this between 50 and perhaps 75 users.

This is together a work for 5 seconds per user to give them directly on the TS3 server any group, which is part of the Ranksystem. 75 user * 5 seconds = 375 seconds ~= 6 minutes

To wrote such a function and check and handle all possible cases, sure this must also be tested and so on...
That will need a couple of hours. Well no, I will not just yet write such a function. Perhaps it will come in future.
