### ISSUE TITLE
Booster

### ISSUE THREAD

**Issue by EGXZ** [Newcomer1989/TSN-Ranksystem#394]
Hi I wanted to ask why sometime when I add someone on the group booster

the ranksystem remove him?

**Comment by Shad86** [comment]
you mean, why the ranksystem removes the boster instantly instead of the set time?

If so, did you remove the group from the User prematurely?

If you do this, the rest of the boost time will be retained in the database and resumed as soon as you reset the group to him.

**Comment by EGXZ** [comment]
Noo you don't get it.

I use a bot that when the user connect in the default channel it add him into the booster group.
but some people the ranksystem remove him from the group booster I dont get why.

**Comment by Shad86** [comment]
So you 100% sure that you never removed may sometime a boost group manually ? Because usually that's exact the behavior, you described.

A boost group only gets removed in 2 cases:

The set time of the boost group is over
or
The group got removed manually in the past, so there was unfinished boost time, so group gets removed earlier or even instant.

**Comment by EGXZ** [comment]
Yeah I think it's the second option.

Thanks for the answer I didn't know.

i'll wait the booster over time and no force remove, thanks you can close.
