### ISSUE TITLE
Database Connection failed: could not find driver

### ISSUE THREAD

**Issue by growndex** [Newcomer1989/TSN-Ranksystem#401]
Database Connection failed: could not find driver
http://prntscr.com/idug10
What's the problem?
I've changed all versions of php .. from 4 to 7. But for nothing.

**Comment by Shad86** [comment]
There seems to be a bug with the installer.php in Release 1.2.4 - pls take take the release -> https://github.com/Newcomer1989/TSN-Ranksystem/archive/1.2.3.zip.

After you installed it and the bot is connected successfully, just send the bot "!update".

If you run into trouble with invalid servergroups, so that you cant fully update, take a look at this thread then:

https://github.com/Newcomer1989/TSN-Ranksystem/issues/398#issuecomment-364884842

i hope i could help you with that.

And last but not least, we try to fix this asap

regards

Shad86

**Comment by growndex** [comment]
ok. Thank's

**Comment by Shad86** [comment]
Fixed.

If you download now https://ts-n.net/downloads/ranksystem_1.2.4.zip a manuell installation is possible.
