### ISSUE TITLE
Database hacked allegedly about the Ranksystem

### ISSUE THREAD

**Issue by hackerpedro** [Newcomer1989/TSN-Ranksystem#41]
Because of this script i got my database hacked and my website wiped out, if it wasn't the owner of the script sure he has a backdoor build in ;)

And I got data center confirmation that was this script that originated the hack...

**Comment by Newcomer1989** [comment]
> Because of this script i got my database hacked and my website wiped out, if it wasn't the owner of the script sure he has a backdoor build in ;)
> 
> And I got data center confirmation that was this script that originated the hack...



These are very hard accusations! As the owner of the script to impute to me, I would have built a backdoor.
I forbid you hereby such unproved accusations! In other accusations I will press charges immediately!

However, if it really is a backdoor inside the script to be, it would be helpful to obtain concrete evidence not just mere allegations. How was the attack carried out? Because it was allegedly confirmed by a data center, the path must be known...
Please report this to me privately and not publish it here! An opportunity for contact exists on the homepage (http://ts-n.net/contact.php)

**Comment by oalaro** [comment]
Considering you didn't have a separate user for ranksystem DB that can't access other DB-s I'd say that you are the one wrong here.

**Comment by Newcomer1989** [comment]
Got a mail from hackerpedro.
In summary: There are nothing concrete. No logs from the hack or anything else...

Its not proven the problem was the Ranksystem! Like oalaro already said, there should be used different users for the Ranksystem and other things (like website). So in this case it could also be the website or any other third-pary-application!

Sure I will check the Ranksystem for potential security risks. Also the code is public, so all other can do this too.
If anyone find a security problem inside the code, they can correct it and make a pull request. Sure it would be better to report that silent to me. So the the problem is not public and could fixed with the next release (in this case hotfix).
