### ISSUE TITLE
TeaSpeak Support

### ISSUE THREAD

**Issue by h1rule** [Newcomer1989/TSN-Ranksystem#529]
Hello,

could you please add the compatible for https://teaspeak.de/ - a alternative for TeamSpeak?

Greetings

**Comment by Newcomer1989** [comment]
What should be supported?

The Ranksystem is able to build a ServerQuery connection.. If TeaSpeak handles this exactly, it should work.
Did you tried it?

**Comment by MrTramp** [comment]
I just tested it yesterday but if it's not working due to TeaSpeak's issues or TSN-Ranksystem sending something wrong I cannot exactly tell. But out of the box it's not working currently.

First issue is that the bot cannot seem to join the channel. Second is that it tries to constantly change the server settings without succeeding.

Will keep testing it though!

Here's the tracelog from a clean TeaSpeak install
[log_2018-08-18_09%3A27%3A50_general.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/2299321/log_2018-08-18_09.3A27.3A50_general.log)

And a log from clean TSN-Ranksystem
[ranksystem.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/2299322/ranksystem.log)

**Comment by Newcomer1989** [comment]
The Ranksystem was developed with the TS3 Server Query Interface.

We used the official documentation by TeamSpeak for this.:
http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

If there is a support in TeaSpeak for the TS3 Query Interface, it should be working without problems. But this you need to ask the developers of TeaSpeak. We cannot answer this.

Also, there seems nothing documented by TeaSpeak. So there is nothing what we can do at the moment!

**Comment by Coolguy3289** [comment]
Documentation links: 
https://github.com/TeaSpeak/TeaSpeak/tree/master/default_files/commanddocs
https://github.com/TeaSpeak/TeaSpeak/blob/master/documentation/ServerQueryNotify.md
https://github.com/TeaSpeak/TeaSpeak/blob/master/documentation/Music bot query interface.md
