### ISSUE TITLE
Please add this feature (""Second kind of rank up...")

### ISSUE THREAD

**Issue by Nexoqq** [Newcomer1989/TSN-Ranksystem#559]
Hi, I love your Ranksystem but I would love it even more if you could add a second "rank-ladder". 
I found this under the "Todo-list" on your website:
"Second kind of rank up, which contains servergroups, that doesn't get removed on next rank up; so they'll stay forever"
Is this something that's going to be added? I would REALLY appreciate that, please!

**Comment by Shad86** [comment]
When and whether we implement the feature that is on our to-do list depends on factors such as time and complexity.

For this reason and because the whole thing is programmed free of charge in our free time, we cannot and will not promise anything.

Nevertheless, we try to fulfill your wishes as best we can.

**Comment by Shad86** [comment]
> "Second kind of rank up, which contains servergroups, that doesn't get removed on next rank up; so they'll stay forever"

implemented
