### ISSUE TITLE
Ranksystem not working after update

### ISSUE THREAD

**Issue by jacopomozzy** [Newcomer1989/TSN-Ranksystem#582]
After the update, I can't login into the webinterface cause when I insert my password the site tell me "wrong password", and the site is missing all the buttons...users lists...I think there is some bugs!

This is my page if you need to see what happening: http://mozzygaming.it/ts3ranks/stats/
What can I do?

regards

**Comment by jacopomozzy** [comment]
It seems like the configuration went deleted...

**Comment by Shad86** [comment]
looks like for me you changed the side navigation under stattspage[Orange] (you can switch it of and on[RED]):

![tsn-statts](https://user-images.githubusercontent.com/18570683/53297853-e09eea80-3824-11e9-9c30-034b6a72577c.png)

if you switch the site -navigation of the sidebar disappear.

Next Problem you now have is, you don't saved your unique Client-ID

This text shows up on your loginpage from your webinterface as long as you wont set it, i think it also shows up after your logged in, because its highly recommended to do that as you wont come in anymore, if you lost your password:

"Please enter the unique Client-ID of the admin of the Ranksystem (Other -> Admin-ID). This is very important in case you lost your login details for the webinterface (to reset these)."

Only last hope for you is, that maybe newcomer has an idea or solution for your current Problem.

But as i can see from here it isn't a Bug

**Comment by jacopomozzy** [comment]
The "bug" is that my password (never changed and auto filledby mozilla  so I can't insert the wrong one) is magically changed!
And also my unique id is not more registered!

**Comment by Newcomer1989** [comment]
Seems to be there went something wrong due the database update.
This shouldn't be a problem, cause before anything will done, the Bot make a backup of all needed tables.

We could offer you to repair this via remote hands. I am the next few time on your TS server online. If you will not reach me there, pls try to contact me on our public TS: ts-n.net

**Comment by jacopomozzy** [comment]
Thanks a lot for everything!

Problem solved.

**Comment by Forge-Media** [comment]
How did you resolve this, same thing I'm experiencing.

Can no longer login, with auto-fill details. Nor can I see the menu options!

Any help would be very welcome!

**Comment by Newcomer1989** [comment]
We did configurated a missed table manually. This is only possible via a remote session.
You can contact us also on the public TS and we could have a look on that problem.
With this method it should be possible to repair all without lost of data.

Alternatevly you could do a fresh installation, but with that you will lost all collected values.

**Comment by Forge-Media** [comment]
I could provide you with connection details to the Database for our TSN install. If this would allow you to fix the problem? I'm not sure what the best method would be to send these sensitive details (email, ts-n.net Teamspeak, etc.)

Thanks for the support!

**Comment by Newcomer1989** [comment]
The best for a remote session would be, when you connect to our public TS3 server and contact me there.

When you connect the next few minutes, we could do it today. But I need to go offline soon.
Otherwise you could try it at 18:00-20:00 UTC the next few days.

**Comment by Forge-Media** [comment]
Thanks @Newcomer1989 

Will keep a lookout on the ts-n teamspeak between 18:00 and 20:00.
