### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by MARL3N** [Newcomer1989/TSN-Ranksystem#594]
Hello, I can not install a rank system on my site, because I do not have root rights for the database. I have one base, but when I enter data on the system of ranks from the base, I get an error.
![149e9f06e170f6691ba870854e889e07](https://user-images.githubusercontent.com/43937273/54884526-39dd5680-4e83-11e9-9916-e1c846672eef.png)
![213e58d2f873695900fd4709c3778e73](https://user-images.githubusercontent.com/43937273/54884527-39dd5680-4e83-11e9-9f6f-b187f2b26e0b.png)

**Comment by Newcomer1989** [comment]
Like the message said: Your database "mar" is still existing.

Please choose a fresh database-name, which is only for the Ranksystem. Be sure, the user have the permissions to this database.
Be also sure, the database isn't still created. The Ranksystem will create the database during the installation process.

**Comment by MARL3N** [comment]
My hosting does not allow creating a database through a script, only manually through hosting

**Comment by Shad86** [comment]
And what exactly do you think we should do now? Sorry but i feel a little bit helpless as you already described that the problem you have is on your side.

Because as you wrote:

> My hosting does not allow creating a database through a script, only manually through hosting

And if you're not able to create more then one database, you can't host it on your own (because as i think the "mar" database is already in use, you would need a second one).

But you can request a hosted solution for free here -> https://ts-ranksystem.com/#hosting

**Comment by MARL3N** [comment]
I installed, but I do not connect to teamspeak.
![f0548e7caa4d3e899721a45d8afea8c2](https://user-images.githubusercontent.com/43937273/54901975-21a02280-4ee9-11e9-8355-f6a26be5b4ad.png)

**Comment by Shad86** [comment]
then check the logs, you can see them if you click on "Start/Stop Bot" on the left side (this also refreshes the logoutput)
![Log-tsn](https://user-images.githubusercontent.com/18570683/54902171-f31a4b80-4ed8-11e9-98e9-5baf3ced34a8.png)

**Comment by MARL3N** [comment]
![f8921b5cb9fb435b0c31f88d0745b081](https://user-images.githubusercontent.com/43937273/54902754-45646800-4eeb-11e9-8616-712c6dc9a3ed.png)

**Comment by Shad86** [comment]
You really set it up? Like insert all the necessary information under TeamSpeak and Core?

**Comment by MARL3N** [comment]
I set everything up https://stats.cists.ru/

**Comment by Shad86** [comment]
hm then im wondering how your log can be empty, if the bot was running like nearly +-16 Days from now on...

It seems you give us wrong/incorrect information again and again...

Because - first you said **today**, you cant install it, then you said **today**, you installed it but it wont start. Now (**still today**) on your site, the bot is running since march 10 '19.

I literally get total new and other information after every question i ask.?!?!?!?

From my point i can't help you here anymore because every answer i get from you is a other situation or problem.

So you can try to come on our support teamspeak and we can try to help you there.
https://ts-ranksystem.com/#support

**Comment by Newcomer1989** [comment]
When you still need help, feel free to contact us like described above.
