### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by Zeemaister** [Newcomer1989/TSN-Ranksystem#607]
Hi. How to change the "TS-N.NET Ranksystem" in the head title?

**Comment by Shad86** [comment]
See it as a little advertise/copyright thingy for our work we do here every day. You can remove it but we wont give instructions for it.

We wont give any support for removing copyright infringement or similar notices of the hints to our ts-ranksystem because in the past many people sold our software as there Software.

The ranksystem itself is distributed under this license -> https://github.com/Newcomer1989/TSN-Ranksystem/blob/master/LICENSE So as we won't getting money for writing the ranksystem and doing support for the ranksystem just give us the little honor and show the World that you use our free open source "product".

kindest regards

Shad86
