### ISSUE TITLE
Bot is disconnecting - flood ban

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#62]
Hey,
I would know, why it Shows me sometimes a message like "This Information is incorrect because the bot isnt connectet" or so on?
And some members are given the rank and some not, why?

**Comment by Shad86** [comment]
"This Information is incorrect because the bot isnt connectet"

Seems your bot lost the connection for some reasons (Thats why it is recommend to make a cronjob who is checking about it if the bot is still running or not)

About the second thing - that happen mostly then, if the bot didnt get started with the right user (do not start it with root rights) - follow the instructions on the site and it should work without any Problems.

**Comment by juvcrafter** [comment]
How do mean this with the cronjob? Can you explain me this as excactly as you can?

And I try to start it with another user.

**Comment by juvcrafter** [comment]
How must I do the informations right in a cronjob? Can you give me Screenshot or so on?

**Comment by Shad86** [comment]
http://ts-n.net/ranksystem.php scroll a little bit down

there is a line with "Installation Linux:"

and its not directly a thing about starting it just with "another user" you have to start it with the webuser if you didnt really have created one but apache is installed just chown the ranksystem folder

for example (in most case if all is on standart this should work):

go to your webfolder

cd /var/www OR cd /var/www/html OR

then

chown www-data:www-data -R /ranksystem 

after that you can start the bot in the right way with following command:

sudo -u www-data php /path/to/your/websever/path/to/ranksystem/worker.php

**cronjob:**

(In vim you have to press "i" to be able to edit the text) (on nano you just can paste the following at the end) 

[PLS Change all things to your right paths!!!!]

`crontab -e`

*/10 * * * * sudo -u www-data php /path/to/your/websever/path/to/ranksystem/worker.php check >/dev/null 2>&1

**Comment by juvcrafter** [comment]
I did everything you said, but it is the same. The bot is disconnecting after some minutes.

**Comment by juvcrafter** [comment]
Is the cronjob right like this? 
http://prntscr.com/bo7j63

**Comment by Shad86** [comment]
if thats you path then yes - is the bot and the TS3-Server are running on the same machine?

Oh i remember something - can you go to /webinterface.php and check 

"Teamspeak Settings" -> "Slowmode" 

there you can choose a delay. 

I think on your Server you have to take a slower one like 0.5 or 1 second after you did that - save it and look if the bot is staying on the ts3 - if not wait about ~5-10 min. - (because cronjob is running each 10 min to check if the bot is running) if the bot isnt connecting.

do the following one time:

`sudo - u www-data php /var/www/html/rank/worker.php restart`

then check again if the can stay on the ts3-server - if not provide or check the logfile if you can find any issues there.

regards

Shad86

**Comment by juvcrafter** [comment]
I tried everything you told me.
I changed the delay to "1", I restartet it, but it doesn´t work.

What can I do now?
It crashes all the time.

**Comment by Shad86** [comment]
As already wrote.

"if not provide or check the logfile you should find an error there if something isnt working well."

regards

Shad86

**Comment by juvcrafter** [comment]
Here you see the log (I think it is the Thing you Need):
http://prntscr.com/bom02i

**Comment by Shad86** [comment]
okay i can see a flood ban there - pls whitelist your ip - also if its the same ip where the ts3-server runs after that it should work finally then :)

**Comment by juvcrafter** [comment]
Which IP must i do on the whitelist? The ts ip? Or the ip, where the bot is runnin´?

**Comment by Shad86** [comment]
the ip where the bot is running

**Comment by Shad86** [comment]
oh and be aware - the Whitelist needs about 5-10min for reloading new rules

**Comment by juvcrafter** [comment]
I try it now and i hope, it will work :)

**Comment by juvcrafter** [comment]
Nice it works. Thanks for your help!

**Comment by par4na** [comment]
It has problem with very large database?
Server statistics not update

http://pastebin.com/wU02S08V

**Comment by par4na** [comment]
It has problem with very large database?
Server statistics not update

http://pastebin.com/wU02S08V

**Comment by Shad86** [comment]
@par4na pls make a new topic with your issue thanks
