### ISSUE TITLE
password reset via email 

### ISSUE THREAD

**Issue by regchanuk** [Newcomer1989/TSN-Ranksystem#676]
please could you implement password reset via email as i forgot my password or ability to email password reminder

**Comment by Shad86** [comment]
usually, if you have set you admin id, you always can reset/recover you're Password
![recover-pw-tsn](https://user-images.githubusercontent.com/18570683/68645519-95467c80-0518-11ea-8619-ce2c2ce265c8.png)

**Comment by regchanuk** [comment]
Admin-ID not found on TS3 server. You need to be online with the unique Client-ID, which is saved as Admin-ID.

**Comment by Shad86** [comment]
3 cases could be the issue:

Before you check the 3 cases below disconnect and reconnect to your teamspeak, then try again the "forgot password" feature. If it wont work:

1. You saved the wrong id into it
2. you were not on the teamspeak
3. you're using different types of protocols like connect on the site with ipv6 and on the teamspeak with ipv4 (you can check that if you visit the mystats site - if you have to verify yourself first, to see the mystats site - then you're using different protocols)

**Comment by regchanuk** [comment]
Did all that I don’t think it saved it properly sonce I missed the =    your hosting me too so cant reset install

**Comment by Shad86** [comment]
then pls write over the contact form -> https://ts-n.net/en/contact.php

**Comment by Newcomer1989** [comment]
When I remember right, your case is still solved since a longer time.

We don't see the necessity for an reset via email. I think the current solution is much more easy with getting the new password via teamspeak chat message.
The only thing is, you need to register your client unique ID during installation / configuring the Ranksystem. You had to ignore several error messages to be not entering it. That could happen with an email address also. Additional you would need to define an email server to be able to send mails, which should be the bigger deal for the most people.
