### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by LeBaasti** [Newcomer1989/TSN-Ranksystem#792]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3.13
Nutzt du TeamSpeak oder TeaSpeak? | Teamspeak
Link zu deiner Ranksystem Statistik Seite | existiert noch nicht
Pastebin Link zu deiner Ranksystem Log *¹ | Nicht da

---

### 1) Was hast du getan?
Ich habe das Ranksystem von meinem alten Server auf meinen neuen Server gezogen.

### 2) Was war deine Erwartung?
Dass ich ganz normal wieder reinkomme, da ich alles wieder aufgesetzt habe.

### 3) Was ist stattdessen passiert?
Ich bekomme diesen Fehler:
![image](https://user-images.githubusercontent.com/48323856/100599509-699f5b80-3300-11eb-9267-9cd43b2e5bdb.png)

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Newcomer1989** [comment]
Have a look to point 3 of the following FAQ entry:
https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem

Be sure, the credentials are correct. Escpecially you created the user correct with "localhost" as host in your case. Or if created with "127.0.0.1" edit the dbconfig.php for the Ranksystem.

**Comment by LeBaasti** [comment]
I checked again, the user was created correctly

**Comment by Newcomer1989** [comment]
Is the user created with "127.0.0.1" or "localhost" ?

**Comment by LeBaasti** [comment]
localhost

**Comment by Newcomer1989** [comment]
On which port or socket is the MariaDB server running?
You should find the options inside the php.ini file.

If it is listening on a TCP port, you should see it on Linux system with this command:
`netstat -tulpn|grep maria`

**Comment by LeBaasti** [comment]
The server runs on the port 3306.

**Comment by Newcomer1989** [comment]
Since questions are only answered in little detail:

Where did you move the server to? What does the infrastructure look like there?

Is it a virtual server, dedicated server, web hosting, etc.?

Do you have root / an admin access?

Which host system do you use Windows / Linux?

Which PHP version is in use?

Is it possible that there are multiple PHP versions installed?

Which PHP command is defined in the `other/phpcommand.php`?
What feedback do you get when you issue this command with the appendix `-v` via a command line?
Example `php -v`

I assume that the PHP extension PHP-PDO is installed and set up as your posted error message says.
But to be on the safe side the demand... Is this the case?

**Comment by LeBaasti** [comment]
Where did you move the server to? What does the infrastructure look like there? I don't know what you mean

Is it a virtual server, dedicated server, web hosting, etc.? Rootserver

Do you have root / an admin access? Full access

Which host system do you use Windows / Linux? Linux

Which PHP version is in use? 
![image](https://user-images.githubusercontent.com/48323856/101169157-d1291400-363c-11eb-83e7-aa5eb02bbf4c.png)


Is it possible that there are multiple PHP versions installed? I don't know

Which PHP command is defined in the other/phpcommand.php? Where can I find this?

I assume that the PHP extension PHP-PDO is installed and set up as your posted error message says.
But to be on the safe side the demand... Is this the case? I am not sure

**Comment by Newcomer1989** [comment]
> Which PHP command is defined in the `other/phpcommand.php`? 

You can find the named file inside the Ranksystem installation folder. By default is the `php` command defined, which should be your php installation 7.4.3.

I would recommend to update your PHP. Currently there is 7.4.13 the latest version of this major release.


If your server runs with multiple PHP versions, you may have different PHP modules for each PHP version. Check the PHP installation from the command out of the `other/phpcommand.php` has installed the PDO extenstion.

```
root@tsn:~# php -m|grep pdo
pdo_mysql
```

At this point you might check, you fullfill the requirements -> https://ts-ranksystem.com/#linux
Please check, you have installed and enabled the listed PHP modules!

```
root@tsn:~# php -m
```

---

>> Where did you move the server to? What does the infrastructure look like there?

> I don't know what you mean

What steps did you do to move the Ranksystem to the current location / server?

We have a description what you need to care of:
https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem

---

I assumed, you already checked the things out of your reported error message. Since you didn't checked the PHP-PDO extension... What is about the database?
Did you created the database on your database server? You imported the the old database from the old server?
Is this database reachable?
Do you have any other script, which is using a database on the same database server? Is this script working?

**Comment by LeBaasti** [comment]
This is the phpcommand.php:
![image](https://user-images.githubusercontent.com/48323856/101241398-e44bea80-36f5-11eb-9787-404334979541.png)

This is the ouput by command php -m|grep pdo:
![image](https://user-images.githubusercontent.com/48323856/101241423-1f4e1e00-36f6-11eb-8f19-ae78d6cd0240.png)

Here the php modules:
![image](https://user-images.githubusercontent.com/48323856/101241467-92f02b00-36f6-11eb-99f7-8695802cd255.png)

What steps did you do to move the Ranksystem to the current location / server?
I used a ftp connection

Did you created the database on your database server? You imported the the old database from the old server? yes
Is this database reachable? yes
Do you have any other script, which is using a database on the same database server? Is this script working? no

**Comment by Newcomer1989** [comment]
Ok, this looks good so far. Your PHP installation should be fine.

Sorry, but I have to close the issue at this point. I really tried hard to ask as good as possible. Nevertheless you answer the questions as short as possible.
How should I know that you have checked it correctly if the answer is only a yes or no.

I am 99% sure, that I asked you already the right question, which had to do with your problem. When you google the error message, it is in >80% of the cases a "localhost" or "127.0.0.1" problem. You said, you checked it. I don't know how you did, cause you doesn't shared us more information. Perhaps have a look again on this point...
