### ISSUE TITLE
MySQL Usage

### ISSUE THREAD

**Issue by Abasalt-yar** [Newcomer1989/TSN-Ranksystem#830]
Hello, While Rank-System Uptime Increases MySQL usage increases too. 
we only use MySQL for Rank-System.
-- | --
Rank system Version | 1.3.17
Are you using TeamSpeak or TeaSpeak? | TeaSpeak 1.4.22
Link to your Ranksystem Stats page | http://biats.ir/stats/
Pastebin Link to your Ranksystem Log

**Comment by Shad86** [comment]
> Hello, While Rank-System Uptime Increases MySQL usage increases too.

First and foremost, I would say that this is normal, because the longer the ranking system runs, the more data to process is written to the database. (New users getting written to the ranksystem, more time per user,....)

So if you say "...While Rank-System Uptime Increases MySQL usage increases too." then my question here would be how does that manifest itself, i.e. how long does the rank system run by what percentage has the whole thing increased (from beginning to end). So, how much usage do you have after a restart, 24h run and 48h run?

regards

Shad86
