### ISSUE TITLE
worker.php check against already running instance

### ISSUE THREAD

**Issue by LordRofl** [Newcomer1989/TSN-Ranksystem#86]
When a cronjob execute the worker.php it can happen that he starts an already running bot.
That may happen when there are different user that starts the bot.

Gruß, 
Drunkenmonkey

**Comment by ryanmemer** [comment]
I had that issue, I was using Plesk and had it as a scheduled task, I had the cronjob using the worker.php as the www-data, I then changed that user to the user who had full accessibility to that directory and it worked fine. 

When I had it using the www-data user, it was making a new query every time the cronjob ran. Which was resulting in the levels to be added/revoked everytime for every bot connected. 

> For example I had 16 queries at one time, if I ranked up; my usergroups would be assigned then revoked 16 times.

**Comment by LordRofl** [comment]
Yes, that is a problem for me, because i can't setup a cronjob with the same user. It´s a hosted webserver and cronjobs are handled with a different system.

Hope they will change the way it checks the query.

**Comment by Newcomer1989** [comment]
I will have a look for this and optimize it.

But I think this will not come with release 1.1.1, but it is noted..

**Comment by ryanmemer** [comment]
This is definitely a bug with version 1.1.0, hoping for a fix in 1.1.1. Thanks for the help

**Comment by Newcomer1989** [comment]
With Version 1.2.10 we will optimize the worker.php for windows.

What we cannot intercept with programming is when wrong permissions or different users are used.
The Ranksystem customer has to make sure that the user of the webserver has the permissions to the full Ranksystem directory. If a cronjob/task is used, the user of the webserver must also be used for this. The same applies to the manual call of worker.php.
If this is not observed correctly, an additional check cannot intercept this, since the rights to the (running) processes of other users may be missing (be able to see processes, end processes, etc.).
