### ISSUE TITLE
Please use the webinterface only via HTTPS!

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#91]
Do I Need  "https" for the new Version?

**Comment by Newcomer1989** [comment]
Https is no requirement to use the webinterface. It will also works great without https. There is no difference in the operation with or without https.

BUT you should use it only via https for security reasons.
Read more [here](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https) for only one example.

I strongly recommend https, that is why I enabled this check.
I also thought about an option to disable this message (to avoid annoying). But I think today there is no more reason to refuse installing a ssl certificate. You get a ssl cert for free today (i.e. letsencrypt.org). So I will not waste time to code an option like this.

**Comment by IMmmKI** [comment]
Hi, 

Anyway you can make it force SSL by an option? or should we rather do that? 

Thanks!!

**Comment by eNNercY1337** [comment]
simply do it via a .htaccess rule.

`RewriteEngine On
RewriteCond %{SERVER_PORT}   !^443$
RewriteRule  (.*)  https://%{HTTP_HOST}/$1   [L]`

**Comment by eNNercY1337** [comment]
i guess this can be closed as it can be simply done with the .htaccess rewrite said above. (after all the best and easiest solution and works on every apache webserver)

**Comment by majoess** [comment]
But not on nginx or iis

**Comment by Newcomer1989** [comment]
I think to force SSL is a generally option, which should be set on the webserver.

Here a link to an example configuration for a nginx webserver.
http://serverfault.com/questions/250476/how-to-force-or-redirect-to-ssl-in-nginx

The Ranksystem does support SSL and warns on the needed place (webinterface). IMHO that is enough.

**Comment by Shad86** [comment]
I also think that this is a good option as it is at the Moment. 

Because many people are really new to this and there are not that into like create a ssl certificate and so on, so they have the option to switch to SSL as soon as the have setup all in the right way.

because if you force it by standart, then it can happen that he never can use it, because in the worst case you cant access the site because there is maybe no ssl port open or available.

I personally think its better in my opinion to let the user know that he can improve his security instead of deny him the whole software/script.
