### ISSUE TITLE
Mode 3 - Assign ranks to users only based on their first server connection

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#93]
I have plenty of users and 3 groups set up on my server, some of them are over 2 years on my server, i want to auto assign group to them immediately as soon as rank system detect them on the server.
Is that possible to do?
(I'm on 1.1.0 now)

**Comment by Shad86** [comment]
The thing is the ranksystem starts counting from the day you start the ranksystem.

**Comment by bykidi** [comment]
But it will be good to see that feature. Get on my place, my users with over 2 years on server have to sit 2 more years to get that group. Kinda crazy, isn't it?

**Comment by Shad86** [comment]
Thats right, but for exact for that "behavior" usually you have the "boost option" only thing you have to to is to set up the boost group and give them one time the boost group and its done.

All other measurements in my opinion are not correct or distort the things.

**Comment by Newcomer1989** [comment]
I think to give user the rank for his first connection would be a really unfair method.

For example: One use (A) connected first in 2014, but was never connected since that time and really starts to be active on the server right now. An other user (B) was first connected in 2015, but was active every day on your server. In this case the user A would have a higher rank then user B. This would be a good system? I think no!

Like Shad86 described it is possible to set this user to a higher rank via the boost function. Only thing you have to do for is to set a boost at once (webinterface). Then for each user you or an other admin give them a special servergroup.
